### PR TITLE
Add note on misspelled words

### PR DESCRIPTION
**Pull request by bact**
- To prevent in the future issues like one at https://bugs.documentfoundation.org/show_bug.cgi?id=163657
- If needed, a license notes on data can be added here as well

### CODE REVIEW

**Review by thep — COMMENTED** [review]
Thanks for the initial contents. I should have clarified the two lists like this:

tdict-spell.txt is for non-standard spellings of words in tdict-std.txt. So, this includes spelling variations that are considered misspelling by the authority.

tdict-common.txt is for words used in real life but are not defined in the standard dictionary. Spelling variations of such words are also included here, as there are no official standard for them yet.

The same applies to other field-specific tdict-*.txt lists. Their spelling variations are included in their respective lists.

**Comment by bact** [comment]
Updated the description to aligned with the clarification above.

Also give few examples for illustration.

**Comment by thep** [comment]
One little detail on the bottom line: tdict-spell.txt was split from tdict-std.txt, not tdict-spell.txt.

**Comment by bact** [comment]
Oh. Fixed krub.

**Pull request merged**
