### PR TITLE
update tdict-city.txt "ตองกา"

### PR DESCRIPTION
**Pull request by topten1222**
add country "ตองกา" in file tdict-city.txt

### CODE REVIEW

**Comment by bact** [comment]
"ตองกา" is already in the country list: https://github.com/tlwg/libthai/blob/master/data/tdict-country.txt#L61

**Comment by topten1222** [comment]
> "ตองกา" is already in the country list: https://github.com/tlwg/libthai/blob/master/data/tdict-country.txt#L61

remove "ตองกา" and add country "คอซอวอ"

**Comment by bact** [comment]
> remove "ตองกา" and add country "คอซอวอ"

Please add country name to `tdict-country.txt`. 

`tdict-city.txt` is for cities.

**Comment by topten1222** [comment]
> > remove "ตองกา" and add country "คอซอวอ"
> 
> Please add country name to `tdict-country.txt`.
> 
> `tdict-city.txt` is for cities.

move city "คอซอวอ" to country.

**Comment by thep** [comment]
Thanks for the addition.

**Pull request merged**
